# Generated by Django 3.1.1 on 2020-10-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20201005_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='list_id',
        ),
        migrations.DeleteModel(
            name='BookmarkSet',
        ),
    ]
