# Generated by Django 3.1.1 on 2020-10-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_bookmark_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='title',
            new_name='site_name',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='owner',
        ),
    ]
